# Generated by Django 4.2.30 on 2026-09-11 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reporting', '0010_taskgroup_collection_taskreport_collection_and_more'),
        ('core', '0076_alter_ocrmodel_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIBackendConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('provider', models.CharField(choices=[('gemini', 'Google Gemini'), ('anthropic', 'Anthropic Claude'), ('openai', 'OpenAI'), ('local', 'Local (OpenAI-compatible: Ollama/vLLM)')], max_length=32)),
                ('model_id', models.CharField(max_length=128)),
                ('endpoint', models.URLField(blank=True, null=True)),
                ('key_ref', models.CharField(blank=True, max_length=128, null=True)),
                ('prompt_template', models.TextField(help_text='Diplomatic-transcription prompt. Colour keys are appended.')),
                ('max_edge_px', models.PositiveIntegerField(default=1024, help_text='Downscale cap — image tokens dominate cost.')),
                ('params', models.JSONField(blank=True, default=dict)),
                ('public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('name', 'owner')},
            },
        ),
        migrations.CreateModel(
            name='AIJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('region', 'Keyed region'), ('line', 'Per-line')], default='region', max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('done', 'Done'), ('error', 'Error')], default='pending', max_length=16)),
                ('prompt_version', models.CharField(blank=True, max_length=64)),
                ('parts_count', models.PositiveIntegerField(default=0)),
                ('lines_written', models.PositiveIntegerField(default=0)),
                ('lines_flagged', models.PositiveIntegerField(default=0, help_text='Skipped/left empty by a pre-flight or bad response.')),
                ('tokens_in', models.BigIntegerField(default=0)),
                ('tokens_out', models.BigIntegerField(default=0)),
                ('est_cost', models.FloatField(default=0.0)),
                ('actual_cost', models.FloatField(default=0.0)),
                ('task_id', models.CharField(blank=True, help_text='Celery task id, set when the worker starts. Not the TaskGroup pk.', max_length=64, null=True)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('backend', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai.aibackendconfig')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_jobs', to='core.document')),
                ('task_group', models.ForeignKey(blank=True, help_text='eScriptorium TaskGroup created at enqueue (ProcessSerializerMixin).', null=True, on_delete=django.db.models.deletion.SET_NULL, to='reporting.taskgroup')),
                ('transcription', models.ForeignKey(help_text='The layer AI output was written to.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.transcription')),
            ],
        ),
        migrations.CreateModel(
            name='AIUsageLedger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=32)),
                ('model_id', models.CharField(max_length=128)),
                ('tokens_in', models.BigIntegerField(default=0)),
                ('tokens_out', models.BigIntegerField(default=0)),
                ('est_cost', models.FloatField(default=0.0)),
                ('actual_cost', models.FloatField(default=0.0)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.document')),
                ('job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='ai.aijob')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIDocumentPolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('never_send_offsite', models.BooleanField(default=False, help_text='If set, only local (Ollama/vLLM) backends may run on this document.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_policy', to='core.document')),
            ],
        ),
    ]
